//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataCollector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap happy {
            get {
                object obj = ResourceManager.GetObject("happy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LoadStory {
            get {
                object obj = ResourceManager.GetObject("LoadStory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;story title=&quot;Man from the South&quot; author=&quot;Roald Dahl&quot;&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;It was getting on towards six o’clock so I thought I&apos;d buy myself a beer and go out and sit in a deckchair by the swimming pool and have a little evening sun.&lt;/part&gt;
        ///		&lt;part&gt;I went to the bar and got the beer and carried it outside and wandered down the garden towards the pool.&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;It was a fine garden with lawns and beds of azaleas and tall coconut palms [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ManFromTheSouth {
            get {
                return ResourceManager.GetString("ManFromTheSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Next {
            get {
                object obj = ResourceManager.GetObject("Next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Remove {
            get {
                object obj = ResourceManager.GetObject("Remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;story title=&quot;Test&quot; author=&quot;TinTin Kalaw&quot;&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;This is a test segment.&lt;/part&gt;
        ///		&lt;part&gt;It has a 2nd part.&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;This is another segment.&lt;/part&gt;
        ///		&lt;part&gt;It has an *italicized* word.&lt;/part&gt;
        ///		&lt;part&gt;Oh look! A very long part fjaksdfajskldjfasdklajsdklfjasdfa. ajdshfajksdhfajsehfjaksdhfasdfjasd. dfkasdjfaefladsjfklasdjflas. dsnfasjefawefkjasdfjaksdfa.&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;This is the last segment.&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;story title=&quot;Man from the South&quot; author=&quot;Roald Dahl&quot;&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segme [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TheFishermanAndTheJinni {
            get {
                return ResourceManager.GetString("TheFishermanAndTheJinni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;story title=&quot;Man from the South&quot; author=&quot;Roald Dahl&quot;&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segment&gt;
        ///	&lt;segment&gt;
        ///		&lt;part&gt;&lt;/part&gt;
        ///	&lt;/segme [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TheVeldt {
            get {
                return ResourceManager.GetString("TheVeldt", resourceCulture);
            }
        }
    }
}
