/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Program3.java
 *
 * Created on 07 11, 11, 3:41:42 PM
 */
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author CEHCI(XPPRO)
 */
public class Program3 extends javax.swing.JFrame {

    /** Creates new form Program3 */
    public Program3() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        filepath = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        filepath.setText("C:\\Users\\CEHCI(XPPRO)\\Desktop\\New folder");
        filepath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filepathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(filepath, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(filepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        filepath.setText(filepath.getText()+"\\");
        File subfolder = new File(filepath.getText());        
        File[] listOfFiles = subfolder.listFiles();
        for (int i = 0; i < listOfFiles.length; i++) {
            if(listOfFiles[i].isFile())
            {BufferedReader bufRdr = null;
            String filename = filepath.getText() + "\\" + listOfFiles[i].getName();
            String context = "none";
            try {
                System.out.println("Reading : " + filename);
                File file = new File(filename);
                bufRdr = new BufferedReader(new FileReader(file));
                String line = null;
                String sample = null;
                int confidence = 0, excitement = 0, interest = 0, frustration = 0;
                int think = 0, hint = 0, answer = 0, mistake = 0;
                String emotion = "neutral";
                int col = 1;
                try {
                    //read each line of text file
                    while ((line = bufRdr.readLine()) != null) {
                        try {
                            // Create file
                            FileWriter fstream = new FileWriter(filepath.getText() + "\\New Folder\\" + listOfFiles[i].getName().replace(".csv", "") + ".csv",true);
                                BufferedWriter out = new BufferedWriter(fstream);
                            out.write(line);
                            //Close the output stream
                            if (col < 14)
                            {
                                out.write(",");
                            }
                            else
                            {
                                out.newLine();
                                col = 0;
                            }
                            col++;
                            out.close();
                            }catch (Exception e){//Catch exception if any
                              System.err.println("Error: " + e.getMessage());
                            }
                        }//while
                    
            } catch (IOException ex) {
                Logger.getLogger(Program3.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {

                //close the file
                bufRdr.close();
            } catch (IOException ex) {
                Logger.getLogger(Program3.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Program3.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                bufRdr.close();
            } catch (IOException ex) {
                Logger.getLogger(Program3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            
         //===========================================
            }//end if
        }//end for loop of files
        //System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void filepathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filepathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filepathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Program3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filepath;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
